import {
  Globe,
  Search,
  ShoppingBag,
  Map,
  Music,
  Video,
  Instagram,
  Twitter,
  MessageCircle,
  Mail,
  Calendar,
  CalendarCheck,
  Camera,
  Cloud,
  FileText,
  MonitorPlay,
  Coffee,
  Utensils,
  Plane,
  PiggyBank,
} from "lucide-react";

export const TOOL_ICONS: Record<string, any> = {
  globe: Globe,
  search: Search,
  shopping: ShoppingBag,
  map: Map,
  music: Music,
  video: Video,
  instagram: Instagram,
  twitter: Twitter,
  message: MessageCircle,
  mail: Mail,
  calendar: Calendar,
  calendarcheck: CalendarCheck,
  camera: Camera,
  cloud: Cloud,
  file: FileText,
  youtube: MonitorPlay,
  coffee: Coffee,
  food: Utensils,
  travel: Plane,
  piggybank: PiggyBank,
};

export const ICON_KEYS = Object.keys(TOOL_ICONS);
